language: generic
sudo: required
services:
- docker
    
before_install:
- docker build -t djsmallman/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true djsmallman/react-test npm test

after_success:
- docker build -t djsmallman/multi-client ./client
- docker build -t djsmallman/multi-nginx ./nginx
- docker build -t djsmallman/multi-server ./server
- docker build -t djsmallman/multi-worker ./worker
# log in to docker cli - updated
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to docker hub
- docker push djsmallman/multi-client
- docker push djsmallman/multi-nginx
- docker push djsmallman/multi-server
- docker push djsmallman/multi-worker

deploy:
provider: elasticbeanstalk
region: eu-west-2
app: multi-docker
env: MultiDocker-env
bucket_name: elasticbeanstalk-eu-west-2-997493607229
bucket_path: docker-multi
on:
branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY



access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY